# Generated by Django 5.0.3 on 2024-03-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('T', 'Trending'), ('P', 'Popular'), ('R', 'Recommended'), ('W', 'Watchlist')], default='T', max_length=1),
        ),
    ]
