# Generated by Django 5.0.3 on 2024-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('T', 'Trending'), ('N', 'Not Trending')], default='T', max_length=1),
        ),
    ]
